### ISSUE TITLE
Link: activeClassName issues

### ISSUE THREAD

**Issue by josebalius** [rackt/react-router#1996]
I am using 1.0.0-beta3, have there been issues reported with this?

Essentially this is my route config:

```
  <Route name="app" component={App} path="/">
    <Route name="login" component={Login} path="login" />

    <Route component={Authenticated}>
      <Route name="home" component={Home} path="home" />
       <Route name="files" component={Files} path="files" />
    </Route>
  </Route>
```

Inside Authenticated I render a `<NavBar />` which contains some links. I have `<Link>` tags with `activeClassName` and the classes seem to set properly when the server renders the app, but as soon as I navigate to a different route, the class does not go away or change to the proper link. If I refresh (server renders) it gets rendered correctly.

I am guessing at some point my route state is getting messed up on the client? If i log something like `this.context.router.isActive('/home')` it renders the correct value (true or false) whenever I navigate to and from the route, but it doesn't change anything in the DOM.

I am thinking it could also be an issue in my project, but wanted to know if you guys could provide me with some direction as to where to look?

**Comment by KyleAMathews** [comment]
Have you tried upgrading to 1.0rc?

**Comment by knowbody** [comment]
I think we fixed those issues, try using 1.0.0-rc1 which is the latest stable version

**Comment by johnz** [comment]
still have the same issue in 1.0.0-rc1, @josebalius is it working for you?

**Comment by knowbody** [comment]
@johnz the problems with `isActive` should be solved, upgrade to RC3 and check if it works for you. [Here](https://github.com/rackt/react-router/blob/master/UPGRADE_GUIDE.md#active-class) you can find more on how to use it, also see the [examples](https://github.com/rackt/react-router/tree/master/examples).

**Comment by johnz** [comment]
just upgraded to rc3 i can confirm its still not working 

this is my routes
<Route component={App}>
            <Route path="/signin" component={SignIn}/>
            <Route component={RequireLogin} onEnter={requireAuth(store)}>
                <Route path="/" component={Home} />
                <Route path="/features" component={Features} />
            </Route>
        </Route>

this is whats in nav component 
<ul className="list-inline navMenu">
        <li><Link activeClassName="activeLink" to={'/'}>App Board</Link></li>
        <li><Link activeClassName="activeLink" to={'/features'}>Features</Link></li>
</ul>

the problem is
- at / activeLink class applied to first link, this is as expected
- when navigate to /features activeLink class still on first link
- when refresh page on /features both links got activeLink class

**Comment by taion** [comment]
https://github.com/rackt/react-router/blob/master/docs/guides/basics/IndexRoutes.md#index-links

**Comment by johnz** [comment]
my problem related to this bug #2212

**Comment by taion** [comment]
As noted, that is fixed on `master` in #2237.

**Comment by johnz** [comment]
awesome thanks @taion !

**Comment by JAdshead** [comment]
update on the URL: [](https://github.com/ReactTraining/react-router/blob/master/docs/guides/IndexRoutes.md#index-links)
