### ISSUE TITLE
Confirm on Navigation ES6 Syntax

### ISSUE THREAD

**Issue by bellicose100xp** [rackt/react-router#2294]
I'm using ES6 Components and react-router 1.0, how to I do something like,

    willTransitionFrom = (component, transition) => {
        if(condition.state.dirty) {
            transition.abort()
        }
    }

all documentation seems to use `Mixins` which I cannot use

**Comment by taion** [comment]
There is _literally_ a link from our docs to a page titled "confirming navigation". I'd suggest you look there.

**Comment by bellicose100xp** [comment]
I read that already, but like I said, it uses 'Mixins' which I cannot use because I'm using the ES6 classes. I'm referring to this page  [Confirm Navigation](https://github.com/rackt/react-router/blob/master/docs/guides/advanced/ConfirmingNavigation.md)

**Comment by taion** [comment]
You have a few options
- Look at the implementation of the mixin
- Use `createClass` for that specific component
- Use any of the half-dozen ways to use mixins with ES6 classes

**Comment by bellicose100xp** [comment]
is there a plan on implementing this lifecycle method without `mixins`

**Comment by gaearon** [comment]
>is there a plan on implementing this lifecycle method without mixins

See above:

>Look at the implementation of the mixin

Here is the [implementation](https://github.com/rackt/react-router/blob/master/modules/Lifecycle.js).
If you use ES6 class, you can put something like that in it.

**Comment by bellicose100xp** [comment]
I've tried implementing it like this,

    Homepage extends React.Component {
     componentDidMount = () => {
            const route = this.props.route || this.context.route;
            this._unlistenBeforeLeavingRoute = this.context.history.listenBeforeLeavingRoute(
            route,
            this.routerWillLeave
        );
     }

    routerWillLeave = nextLocation => {
        if(this.state.dirty) {
            return 'You have some unsaved changes! Are you sure you want to leave?';
        }
    }

    componentWillUnmount = () => {
        if (this._unlistenBeforeLeavingRoute) {
            this._unlistenBeforeLeavingRoute();
        }
    }
    }

    Homepage.contextTypes = {
        history: React.PropTypes.object,
        location: React.PropTypes.object,
        route: React.PropTypes.object
    };

    Homepage.propTypes = {
        route: React.PropTypes.object
    };

i'm getting the following error when i try to navigate away, `Uncaught TypeError: Cannot read property 'search' of undefined` 

Is there something I'm failing to implement?

**Comment by taion** [comment]
Possibly the bug fixed by https://github.com/rackt/react-router/commit/6f8ceac463f49f96bec7d429071c5bd3746c1e7c.

**Comment by bellicose100xp** [comment]
I made the change in the that fix at this location `node_modules/react-router/modules/useRoutes.js` and still get the same error..

**Comment by bellicose100xp** [comment]
I've tried all routes including using react-mixin but it refuses to work when I use the es6 classes.. I'll wait until there's a implementation of this for for ES6 directly..
