### ISSUE TITLE
Redirect to "/" causes SecurityError when HTML <base> tag is set to "href=/"

### ISSUE THREAD

**Issue by philipflesher** [rackt/react-router#2960]
When a ```<base href="/">``` tag is present in the document head, using a Redirect route from the root to ```\``` causes the ```addBasename``` function to improperly set a basename of ```\``` and a pathname of ```\```. This leads to a an attempted redirect to ```\\```, which is interpreted as a naked ```https:``` (or whatever the current protocol context is) - which throws the following error:

```Uncaught SecurityError: Failed to execute 'replaceState' on 'History': A history state object with URL 'https:' cannot be created in a document with origin 'https://www.whatever.com'.```

Here's the full routing configuration I'm using:

```
  <Router history={browserHistory}>
    <Route path="/">
      <IndexRoute component={RootRedirectComponent} />
      <Route path="login" component={LoginPage} onEnter={redirectIfLoggedIn} />
      <Route path="register" component={UserRegistrationPage} onEnter={redirectIfLoggedIn} />
      <Route path="profile" component={EditProfilePage} onEnter={requireLogin} />
      <Route path="users/:username" component={UserPage} />
    </Route>
    <Redirect from="**" to="/" />
  </Router>
```

I don't understand the purpose of the following line in ```addBasename```, which might be removable to fix the issue. I hesitated issuing a PR without understanding the necessity of appending the trailing ```\``` in all cases:

```
if (location.pathname === '') location.pathname = '/';
```

**Comment by taion** [comment]
Dupe of https://github.com/rackt/react-router/issues/2917, probably fixed with next history release.

**Comment by tyrsius** [comment]
@taion I am on history 2.0 and I am still experiencing this bug

**Comment by tyrsius** [comment]
Looks like router 2.3 doesn't have this, The linked issue said 2.0 and I got confused.
