### ISSUE TITLE
browserHistory.replace() reloads page in Chrome for iOS

### ISSUE THREAD

**Issue by dfoverdx** [rackt/react-router#3000]
I'm not sure if this is a bug in browserHistory or the iOS Chrome app, since it only occurs in that browser--not in the iOS Google app, Safari for iOS, Chrome for Windows, or Microsoft Edge--but when I call history.replace(), the url changes and the page reloads, rather than just updating the url and route.

**Comment by taion** [comment]
Fixed on master of history.

**Comment by dfoverdx** [comment]
I'm not super familiar with how npm works... just enough to get by.  I ran `npm install history` and `npm install react-router`, and I still have the same issue.  Do I need to pull a specific version of history or something?

**Comment by taion** [comment]
No, it's not release yet.
