### ISSUE TITLE
Support React version 0.13

### ISSUE THREAD

**Issue by gaearon** [rackt/react-router#638]
React 0.13 brings [parent-based context instead of owner-based context](https://github.com/facebook/react/issues/2112).

I'm getting tons of warnings with just published [react@0.13.0-alpha.1](https://github.com/facebook/react/commit/3fec78638deb5926b25063dc9f3fe8eef5140751) and the main problem seems to be that context is defined on router (`makePath`, `makeHref`, `transitionTo`, `replaceWith`, etc) but we're giving `RouteHandler` in render, so these keys don't appear in `RouteHandler`'s parent-based context.

I still can't think quite straight about these changes but I assume some kind of wrapping `RouteHandler` into context parent will be necessary.

Edit (@mjackson): let's keep a checklist here:

- [ ] fix errors due to reliance on auto-binding. this will probably be clearer once we refactor `Router` into a proper class instead of the hybrid it is today
- [ ] stop using `createClass().type` (thanks @taurose)
- [x] only keep `router` on context (see #744 / #855)

**Comment by gurdasnijor** [comment]
I can has 0.13 support?  :smile:

**Comment by taurose** [comment]
Just did some testing and here's the issues I've found thus far:

1. **createClass static methods aren't automatically bound anymore**
Causes an error in `router.handleLocationChange`, since the method is passed as is to `Locations`. Could be a bug in react, not sure. See #818.

2. **createClass().type is deprecated**
In Routing.js, we simply have to replace checks like `element.type === Redirect.type` with `element.type === Redirect`. Not backwards-compatible, though.

3. **Context changes**
The way I understand it, this isn't even a parent vs owner context problem. In order to support and compare the two context mechanisms, react calls `getChildContext` twice. Since we're doing stuff like `.bind` and `.concat`, the identity checks will fail and the warnings will show up. I guess this is best fixed with #744 (only put `router` object on context).

**Comment by mjackson** [comment]
Just FYI, I'm working on 0.13 support in the [0.13-compat branch](https://github.com/rackt/react-router/tree/0.13-compat)

**Comment by gurdasnijor** [comment]
Timing couldn't be better :)

http://facebook.github.io/react/blog/2015/02/24/react-v0.13-rc1.html

**Comment by Stoney-FD** [comment]
@mjackson Thanks for the compat branch. I'm having some issues there. The initial/default route works fine, but when I try to change to another route through the URL, I'm getting:
```
react-router.js:1603 Uncaught TypeError: Cannot read property 'dispatch' of undefined
react-router.js:1603 handleLocationChange
react-router.js:445 (anonymous function)
react-router.js:444 notifyChange
react-router.js:457 onHashChange
```
And nothing else happens.

I'm pretty new to React and react-router, but if anyone could give me some pointers, I'd like to take a crack at it.

**Comment by fczuardi** [comment]
My experience so far in trying to make **rack/react-router#0.13-compat** work with **react@0.13.0-rc2** :

- it doesn't work out of the box because the modules of react-router use ES6 syntax
  - bundling with browserify and reactify won't work, even if the es6 option is setted true
  - making a copy of node_modules/react-router and running babel on it to convert to es5 was the path that worked for me
- Once you have a es5 converted version of react-router, ```<Link />``` components or ```transitionTo``` api calls on components with the mixin will change the path in your location bar, but not re-render your main component
  - the ugly workaround was to call ```React.unmountComponentAtNode(document.body);``` in the callback right before the ```React.render(<Handler/>, document.body);```
    - this feels very wrong and maybe even defeat the purpose of using react's diff, I don't know if it might be necessary due to a bug in my code, or a bug in react-router, or in react itself. Probably in my code, I will try to create a reduced test case to share.

**Comment by gaearon** [comment]
>making a copy of node_modules/react-router and running babel on it to convert to es5 was the path that worked for me

There's a build step to do this, happens before publishing to NPM.

**Comment by fczuardi** [comment]
Oh, I see it, https://github.com/rackt/react-router/blob/master/package.json#L14,  ```npm run build-npm``` should work then, I will give it a try.

**Comment by chollier** [comment]
I get some : 
```
Warning: owner-based and parent-based contexts differ (values: `[object Object],[object Object]` vs `[object Object],[object Object]`) for key (routeHandlers) while mounting RouteHandler (see: http://fb.me/react-context-by-parent)
```

 and my final RouteHandler doesn't render.

**Comment by chollier** [comment]
Which doesn't seem a problem, however when opening a new tab and hitting a route, I get :
```
Uncaught ReferenceError: _currentRoute is not defined         Route.js:52
```

but when refreshing the page it goes right.

**Comment by pilwon** [comment]
v0.13 has just been released: http://facebook.github.io/react/blog/2015/03/10/react-v0.13.html

**Comment by johanneslumpe** [comment]
@chollier That actually seems weird to me, because `_currentRoute` is a global inside the module, it should always be defined.

Just tried to run the compat branch with react 0.13 - tons of errors. Not sure where to start fixing them. Tried to add `contextTypes` to the nested test component, just to see if that helps with the owner/parent context mismatch, because the nested component renders the `RouteHandler`, which requires those context props. But no luck with that.

@ryanflorence @mjackson any pointers where exactly help is required and what currently is already being worked on to fix the compat issues?

**Comment by daviferreira** [comment]
Should we work based on the compat branch?

**Comment by nhunzaker** [comment]
I noticed in this branch that the 0.13 class syntax is being used. Does this mean that the `0.13-compat` branch will not be backwards compatible?

**Comment by gaearon** [comment]
Router can still be used both in new and old style components. This is not changing.

**Comment by nhunzaker** [comment]
@gaearon Yes, but this branch defines the Route components with the 0.13 class syntax. Unless I am mistaken, this eliminates 0.12 support.

**Comment by gaearon** [comment]
Oh, sorry, I misunderstood your question. When React bumps major version, next version of RR comes out requiring it. So yes, React Router 0.13 won't support React 0.12, as far as I know.

**Comment by nhunzaker** [comment]
@gaearon :+1: That'll make the `Component.type` issue quite a bit easier to address

**Comment by nhunzaker** [comment]
I think I fixed 0.13, but I don't really know yet. Would anyone be willing to verify my 0.13.0 branch?

https://github.com/rackt/react-router/compare/rackt:0.13-compat...nhunzaker:0.13.0?expand=1

**Comment by pilwon** [comment]
@nhunzaker It's working! :+1:

**Comment by nhunzaker** [comment]
Related: https://github.com/rackt/react-router/pull/948

**Comment by chollier** [comment]
@johanneslumpe nevermind I also get that with 0.12

**Comment by bloodyowl** [comment]
I created a PR to fix the owner vs parent context here : #959

**Comment by pilwon** [comment]
I'm just curious because it's been about a month since React v0.13 was released and almost half a year since this issue was originally created. Is someone actually working on this or are we all just waiting for someone to take on this challenge and solve the problem?

**Comment by woodb** [comment]
@pilwon I'm pretty sure that this already supports React 0.13, I'm not sure why it's still open... Following the [upgrade guide](https://github.com/rackt/react-router/blob/master/UPGRADE_GUIDE.md) made it pretty easy to make the changes necessary for React 0.13.

**Comment by Ismael** [comment]
The issue hasn't been updated, but the latest version supports react 0.13.

**Comment by pilwon** [comment]
That is a fantastic news. Thanks guys :+1:

**Comment by thealjey** [comment]
This has been fixed a while ago actually, tested with react 13.1, and it's pretty great to say the least.
The best extension for the ultimate framework!
Thanks for this, and I bow bow down before your awesome smartitude :bow:

**Comment by fatso83** [comment]
The warnings introduced with the 0.12->0.13 upgrade still appear disappear: 

```Warning: owner-based and parent-based contexts differ (values: `[object Object]` vs `[object Object]`) for key (routeHandlers) while mounting RouteHandler```

So until that is sorted out, I cannot see how you can say that has been fixed, @thealjey Do agree that it is functionally working, though.

**Comment by woodb** [comment]
@fatso83 have you gone through the [migration guide](https://github.com/rackt/react-router/blob/master/UPGRADE_GUIDE.md)?

We're using `react 0.13.1`, `react-router 0.13.2` and `node v0.12.1` and are not receiving any warnings, though we were before going through the guide...

**Comment by fatso83** [comment]
@woodb Yeah, as it's public, you can see that I follow the upgrade guide [pretty close](https://github.com/fatso83/Emissions/blob/master/app/main.js). Not really doing any fanciness (no Mixins), just [basic route setup](https://github.com/fatso83/Emissions/blob/master/app/routes.react.js), one sub-level using [RouteHandler](https://github.com/fatso83/Emissions/blob/master/app/components/app.react.js) and [router.run()](https://github.com/fatso83/Emissions/blob/master/app/main.js). So not sure why I get these warnings.

**Comment by deakster** [comment]
@fatso83 In dev mode you are using your build/jslib/react-router.js file. I don't believe that's react-router 0.13.2, since replacing that with the actual react-router 0.13.2 gets rid of the warnings for me.

**Comment by fatso83** [comment]
@deakster Thanks for checking that! I'll gladly shut up and never utter a word on GH again. No clue what version of react-router that was either. Maybe that could be a clue to add the version info at build time like React does? Think I'll go hide under a rock for a few weeks now.

**Comment by saulshanabrook** [comment]
@gaearon should this be closed then?

**Comment by gaearon** [comment]
Yep.
React Router 0.13 supports React 0.13.
